#!/bin/sh
#set -x

TOOL_NAME="Microsoft Office CDN Version Check"
TOOL_VERSION="2.5"

## Copyright (c) 2019 Microsoft Corp. All rights reserved.
## Scripts are not supported under any Microsoft standard support program or service. The scripts are provided AS IS without warranty of any kind.
## Microsoft disclaims all implied warranties including, without limitation, any implied warranties of merchantability or of fitness for a 
## particular purpose. The entire risk arising out of the use or performance of the scripts and documentation remains with you. In no event shall
## Microsoft, its authors, or anyone else involved in the creation, production, or delivery of the scripts be liable for any damages whatsoever 
## (including, without limitation, damages for loss of business profits, business interruption, loss of business information, or other pecuniary 
## loss) arising out of the use of or inability to use the sample scripts or documentation, even if Microsoft has been advised of the possibility
## of such damages.
## Feedback: pbowden@microsoft.com

# Constants
MAUID_MAU4X="0409MSAU04"
MAUID_WORD2016="0409MSWD15"
MAUID_WORD2019="0409MSWD2019"
MAUID_EXCEL2016="0409XCEL15"
MAUID_EXCEL2019="0409XCEL2019"
MAUID_POWERPOINT2016="0409PPT315"
MAUID_POWERPOINT2019="0409PPT32019"
MAUID_OUTLOOK2016="0409OPIM15"
MAUID_OUTLOOK2019="0409OPIM2019"
MAUID_ONENOTE2016="0409ONMC15"
MAUID_ONENOTE2019="0409ONMC2019"
MAUID_ONEDRIVE="0409ONDR18"
MAUID_TEAMS="0409TEAM01"
MAUID_OFFICE2011="0409MSOF14"
MAUID_LYNC2011="0409UCCP14"
MAUID_SKYPE2016="0409MSFB16"
MAUID_REMOTEDESKTOP="0409MSRD10"
MAUID_COMPANYPORTAL="0409IMCP01"
MAUID_EDGEBETA="0409EDBT01"
MAUID_EDGECANARY="0409EDCN01"
MAUID_EDGEDEV="0409EDDV01"
MAUID_DEFENDER="0409WDAV00"
CHANNEL_COLLATERAL_PROD="http://officecdn.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/"
CHANNEL_COLLATERAL_INSIDERSLOW="http://officecdn.microsoft.com/pr/1ac37578-5a24-40fb-892e-b89d85b6dfaa/MacAutoupdate/"
CHANNEL_COLLATERAL_INSIDERFAST="http://officecdn.microsoft.com/pr/4B2D7701-0A4F-49C8-B4CB-0C2D4043F51F/MacAutoupdate/"
CHANNEL_COLLATERAL_MSFT="http://officecdn.microsoft.com/pr/03adf619-38c6-4249-95ff-4a01c0ffc962/MacAutoupdate/"
CHANNEL_COLLATERAL_DOGFOOD="http://officecdn.microsoft.com/pr/e2e9e618-e7cc-4681-a831-2f1eb16e7354/MacAutoupdate/"
SCRATCH_AREA="$TMPDIR""OfficeCDNCheck"

## Formatting support
TEXT_RED='\033[0;31m'
TEXT_YELLOW='\033[0;33m'
TEXT_GREEN='\033[0;32m'
TEXT_BLUE='\033[0;34m'
TEXT_NORMAL='\033[0m'

# Platform detection
PLATFORM=$(uname -s)

# Shows tool usage and parameters
function ShowUsage() {
	echo $TOOL_NAME - $TOOL_VERSION
	echo "Purpose: Reports which versions of Office apps are available on the Content Delivery Network (CDN)"
	echo "Usage: OfficeCDNCheck [--Production] [--InsiderSlow] [--InsiderFast] [--AllChannels] [--Local] [--Azure] [--Akamai] [--ChinaCache] [--AllProviders]"
	echo
	exit 0
}

# Creates and cleans temporary file area
function InitializeScratchArea() {
	if [ -d "$SCRATCH_AREA" ]; then
		rm -d -r -i -f "$SCRATCH_AREA"
	fi
	mkdir "$SCRATCH_AREA"
	mkdir "$SCRATCH_AREA"/"Prod"
	mkdir "$SCRATCH_AREA"/"Prod/Akamai"
	mkdir "$SCRATCH_AREA"/"Prod/Azure"
	mkdir "$SCRATCH_AREA"/"Prod/ChinaCache"
	mkdir "$SCRATCH_AREA"/"Prod/Local"
	mkdir "$SCRATCH_AREA"/"Insider_Slow"
	mkdir "$SCRATCH_AREA"/"Insider_Slow/Akamai"
	mkdir "$SCRATCH_AREA"/"Insider_Slow/Azure"
	mkdir "$SCRATCH_AREA"/"Insider_Slow/ChinaCache"
	mkdir "$SCRATCH_AREA"/"Insider_Slow/Local"
	mkdir "$SCRATCH_AREA"/"Insider_Fast"
	mkdir "$SCRATCH_AREA"/"Insider_Fast/Akamai"
	mkdir "$SCRATCH_AREA"/"Insider_Fast/Azure"
	mkdir "$SCRATCH_AREA"/"Insider_Fast/ChinaCache"
	mkdir "$SCRATCH_AREA"/"Insider_Fast/Local"
	mkdir "$SCRATCH_AREA"/"Microsoft"
	mkdir "$SCRATCH_AREA"/"Microsoft/Akamai"
	mkdir "$SCRATCH_AREA"/"Microsoft/Azure"
	mkdir "$SCRATCH_AREA"/"Microsoft/ChinaCache"
	mkdir "$SCRATCH_AREA"/"Microsoft/Local"
	mkdir "$SCRATCH_AREA"/"Dogfood"
	mkdir "$SCRATCH_AREA"/"Dogfood/Akamai"
	mkdir "$SCRATCH_AREA"/"Dogfood/Azure"
	mkdir "$SCRATCH_AREA"/"Dogfood/ChinaCache"
	mkdir "$SCRATCH_AREA"/"Dogfood/Local"
}

# Selects the CDN provider
function ResolveDownloadUrl() {
	PROVIDER="$2"
	if [ "$PROVIDER" == "Akamai" ]; then
		HTTPURL=(${1/https/https})
		FILEURL=(${HTTPURL/officecdn.microsoft.com/officecdn-microsoft-com.akamaized.net})
	elif [ "$PROVIDER" == "Azure" ]; then
		HTTPURL=(${1/https/http})
		FILEURL=(${HTTPURL/officecdn.microsoft.com/C2R.a-0020.a-msedge.net})
	elif [ "$PROVIDER" == "ChinaCache" ]; then
		HTTPURL=(${1/https/http})
		FILEURL=(${HTTPURL/officecdn.microsoft.com/officecdn.microsoft.com.chinacache.net})
	else
		FILEURL="$1"
	fi
	echo "$FILEURL"
}

# Builds an array of all the MAU-enabled applications that we care about
function BuildApplicationArray() {
	MAUAPP=""
	MAUAPP[0]="$MAUID_MAU4X"
	MAUAPP[1]="$MAUID_WORD2016"
	MAUAPP[2]="$MAUID_WORD2019"
	MAUAPP[3]="$MAUID_EXCEL2016"
	MAUAPP[4]="$MAUID_EXCEL2019"
	MAUAPP[5]="$MAUID_POWERPOINT2016"
	MAUAPP[6]="$MAUID_POWERPOINT2019"
	MAUAPP[7]="$MAUID_OUTLOOK2016"
	MAUAPP[8]="$MAUID_OUTLOOK2019"
	MAUAPP[9]="$MAUID_ONENOTE2016"
	MAUAPP[10]="$MAUID_ONENOTE2019"
	MAUAPP[11]="$MAUID_ONEDRIVE"
	MAUAPP[12]="$MAUID_TEAMS"
	MAUAPP[13]="$MAUID_OFFICE2011"
	MAUAPP[14]="$MAUID_LYNC2011"
	MAUAPP[15]="$MAUID_SKYPE2016"
	MAUAPP[16]="$MAUID_REMOTEDESKTOP"
	MAUAPP[17]="$MAUID_COMPANYPORTAL"
	MAUAPP[18]="$MAUID_EDGEBETA"
	MAUAPP[19]="$MAUID_EDGECANARY"
	MAUAPP[20]="$MAUID_EDGEDEV"
	MAUAPP[21]="$MAUID_DEFENDER"
}

# Builds an array of MAU collateral file-paths which we'll use later for downloading XML and CAT files
function BuildCollateralArray() {
	DOWNLOADARRAY=""
	DOWNLOADARRAY[0]="$1"$MAUID_MAU4X
	DOWNLOADARRAY[1]="$1"$MAUID_WORD2016
	DOWNLOADARRAY[2]="$1"$MAUID_WORD2019
	DOWNLOADARRAY[3]="$1"$MAUID_EXCEL2016
	DOWNLOADARRAY[4]="$1"$MAUID_EXCEL2019
	DOWNLOADARRAY[5]="$1"$MAUID_POWERPOINT2016
	DOWNLOADARRAY[6]="$1"$MAUID_POWERPOINT2019
	DOWNLOADARRAY[7]="$1"$MAUID_OUTLOOK2016
	DOWNLOADARRAY[8]="$1"$MAUID_OUTLOOK2019
	DOWNLOADARRAY[9]="$1"$MAUID_ONENOTE2016
	DOWNLOADARRAY[10]="$1"$MAUID_ONENOTE2019
	DOWNLOADARRAY[11]="$1"$MAUID_ONEDRIVE
	DOWNLOADARRAY[12]="$1"$MAUID_TEAMS
	DOWNLOADARRAY[13]="$1"$MAUID_OFFICE2011
	DOWNLOADARRAY[14]="$1"$MAUID_LYNC2011
	DOWNLOADARRAY[15]="$1"$MAUID_SKYPE2016
	DOWNLOADARRAY[16]="$1"$MAUID_REMOTEDESKTOP
	DOWNLOADARRAY[17]="$1"$MAUID_COMPANYPORTAL
	DOWNLOADARRAY[18]="$1"$MAUID_EDGEBETA
	DOWNLOADARRAY[19]="$1"$MAUID_EDGECANARY
	DOWNLOADARRAY[20]="$1"$MAUID_EDGEDEV
	DOWNLOADARRAY[21]="$1"$MAUID_DEFENDER
}

# Downloads XML/CAT collateral files
function DownloadCollateralFiles() {
	for i in "$@"
	do
		#echo Downloading collateral file: "$i"
		if [ "$PROVIDER" == "Azure" ] || [ "$PROVIDER" == "ChinaCache" ]; then
			(cd "$SCRATCH_AREA"/"$CHANNEL"/"$PROVIDER" && curl --silent --remote-name --location --header 'Host:officecdn.microsoft.com' "$i{.xml,.cat,-chk.xml}")
		else
			(cd "$SCRATCH_AREA"/"$CHANNEL"/"$PROVIDER" && curl --silent --remote-name --location "$i{.xml,.cat,-chk.xml}")
		fi
	done
}

# Returns the current app version from the XML collateral
function GetAppVersionFromXML() {
	local XML="$1"".xml"
	local CHAN="$2"
	local PROV="$3"
	if [ "$1" == "0409MSOF14" ]; then
		local APPVER=$(cd "$SCRATCH_AREA"/"$CHAN"/"$PROV" && grep -o '<string>Office 2011.*' $1".xml" | cut -d'>' -f2 | cut -d'<' -f1 | tail -1 | cut -d' ' -f 3)
	elif [ "$1" == "0409UCCP14" ]; then
		local APPVER=$(cd "$SCRATCH_AREA"/"$CHAN"/"$PROV" && grep -o -m 1 '<string>Lync 14.*' $1".xml" | cut -d'>' -f2 | cut -d'<' -f1 | cut -d' ' -f 2)
	else
		local APPVER=($(cd "$SCRATCH_AREA"/"$CHAN"/"$PROV" && grep -o -A1 -m2 'Update Version' "$XML" | grep 'string' | sed -e 's,.*<string>\([^<]*\)</string>.*,\1,g'))
	fi
	if [ "$APPVER" == '' ]; then
		echo "Undetermined"
	else
		echo "$APPVER"
	fi
}

# Returns the SHA1 hash from the CAT
function GetHashFromCAT() {
	local CAT="$1"".cat"
	local CHAN="$2"
	local PROV="$3"
	local CATHASH=($(cd "$SCRATCH_AREA"/"$CHAN"/"$PROV" && openssl sha1 "$CAT" | cut -d'=' -f2))
	if [ "$CATHASH" == '' ]; then
		echo "Undetermined"
	else
		echo "$CATHASH"
	fi
}

# Performs a reverse look-up from MAUID to friendly name
function GetAppNameFromMAUID() {
	case "$1" in
		$MAUID_MAU4X)			APPNAME="MAU 4.x"
								;;
		$MAUID_WORD2016)		APPNAME="Word 2016"
								;;
		$MAUID_WORD2019)		APPNAME="Word 2019"
								;;
		$MAUID_EXCEL2016)		APPNAME="Excel 2016"
								;;
		$MAUID_EXCEL2019)		APPNAME="Excel 2019"
								;;
		$MAUID_POWERPOINT2016)		APPNAME="PowerPoint 2016"
								;;
		$MAUID_POWERPOINT2019)		APPNAME="PowerPoint 2019"
								;;
		$MAUID_OUTLOOK2016)		APPNAME="Outlook 2016"
								;;
		$MAUID_OUTLOOK2019)		APPNAME="Outlook 2019"
								;;
		$MAUID_ONENOTE2016)		APPNAME="OneNote 2016"
								;;
		$MAUID_ONENOTE2019)		APPNAME="OneNote 2019"
								;;
		$MAUID_ONEDRIVE)		APPNAME="OneDrive"
								;;
		$MAUID_TEAMS)			APPNAME="Teams"
								;;
		$MAUID_OFFICE2011)		APPNAME="Office 2011"
								;;
		$MAUID_LYNC2011)		APPNAME="Lync 2011"
								;;
		$MAUID_SKYPE2016)		APPNAME="Skype for Business 2016"
								;;
		$MAUID_REMOTEDESKTOP)		APPNAME="Remote Desktop v10.x"
								;;
		$MAUID_COMPANYPORTAL)		APPNAME="Intune Company Portal"
								;;
		$MAUID_EDGEBETA)		APPNAME="Edge Beta"
								;;
		$MAUID_EDGECANARY)		APPNAME="Edge Canary"
								;;
		$MAUID_EDGEDEV)			APPNAME="Edge Dev"
								;;
		$MAUID_DEFENDER)		APPNAME="Defender ATP"
								;;
	esac
	echo "$APPNAME"
}

# Performs a reverse look-up from FFN to friendly name
function GetChannelFromFFN() {
	case "$1" in
		$CHANNEL_COLLATERAL_PROD)			CHANNELNAME="Prod"
								;;
		$CHANNEL_COLLATERAL_INSIDERSLOW)		CHANNELNAME="Insider_Slow"
								;;
		$CHANNEL_COLLATERAL_INSIDERFAST)		CHANNELNAME="Insider_Fast"
								;;
		$CHANNEL_COLLATERAL_MSFT)			CHANNELNAME="Microsoft"
								;;
		$CHANNEL_COLLATERAL_DOGFOOD)			CHANNELNAME="Dogfood"
								;;
	esac
	echo "$CHANNELNAME"
}

# Evaluate command-line arguments
if [[ $# = 0 ]]; then
	ShowUsage
else
	for KEY in "$@"
	do
	case $KEY in
    	--Help|-h|--help)
    	ShowUsage
    	shift # past argument
    	;;
    	--Production|-pr|--production)
		PROD=true
    	shift # past argument
    	;;
    	--InsiderSlow|-is|--insiderslow)
		SLOW=true
    	shift # past argument
    	;;
    	--InsiderFast|-if|--insiderfast)
		FAST=true
    	shift # past argument
    	;;
    	--Microsoft|-ms|--microsoft)
		MSFT=true
    	shift # past argument
    	;;
    	--Dogfood|-df|--dogfood)
		DOGF=true
    	shift # past argument
    	;;
    	--AllChannels|-ac|--allchannels)
    	ALLCHANNELS=true
    	shift # past argument
    	;;
    	--Local|-l|--local)
    	LOCAL=true
    	shift # past argument
    	;;
    	--Azure|-az|--azure)
    	AZURE=true
    	shift # past argument
    	;;
    	--Akamai|-ak|--akamai)
    	AKAMAI=true
    	shift # past argument
    	;;
    	--ChinaCache|-ch|--chinacache)
    	CHINA=true
    	shift # past argument
    	;;
    	--AllProviders|-ap|--allproviders)
    	ALLPROVIDERS=true
    	shift # past argument
    	;;
    	*)
    	ShowUsage
    	;;
	esac
	shift # past argument or value
	done
fi

## Main

# Get a clean area for writing temporary files
InitializeScratchArea
# Build channel array
CHANNELS=()
if [ $PROD ] || [ $ALLCHANNELS ]; then
	CHANNELS+=("$CHANNEL_COLLATERAL_PROD")
fi
if [ $SLOW ] || [ $ALLCHANNELS ]; then
	CHANNELS+=("$CHANNEL_COLLATERAL_INSIDERSLOW")
fi
if [ $FAST ] || [ $ALLCHANNELS ]; then
	CHANNELS+=("$CHANNEL_COLLATERAL_INSIDERFAST")
fi
if [ $MSFT ]; then
	CHANNELS+=("$CHANNEL_COLLATERAL_MSFT")
fi
if [ $DOGF ]; then
	CHANNELS+=("$CHANNEL_COLLATERAL_DOGFOOD")
fi

# Routine for all channels in the array
for c in "${CHANNELS[@]}"
do
	# Get friendly channel name
	CHANNEL=$(GetChannelFromFFN "$c")
	echo
	echo "${TEXT_RED}Channel: $CHANNEL ${TEXT_NORMAL}"
	PROVIDERS=()
	if [ $LOCAL ] || [ $ALLPROVIDERS ]; then
		PROVIDERS+=("Local")
	fi
	if [ $AZURE ] || [ $ALLPROVIDERS ]; then
		PROVIDERS+=("Azure")
	fi
	if [ $AKAMAI ] || [ $ALLPROVIDERS ]; then
		PROVIDERS+=("Akamai")
	fi
	if [ $CHINA ] || [ $ALLPROVIDERS ]; then
		PROVIDERS+=("ChinaCache")
	fi
	if [ ${#PROVIDERS[@]} -eq 0 ]; then
		PROVIDERS+=("Akamai")
	fi

	for p in "${PROVIDERS[@]}"
	do
		PROVIDER="$p"
		echo "${TEXT_BLUE}   Provider: $PROVIDER ${TEXT_NORMAL}"
		# Resolve collateral download URL
		COLLATERALURL=$(ResolveDownloadUrl "$c" "$PROVIDER")
		# Build an array of the collateral files to download
		BuildCollateralArray "$COLLATERALURL"
		# Download collateral files for each application
		DownloadCollateralFiles "${DOWNLOADARRAY[@]}"
		# Build an array of all MAU-enabled applications
		BuildApplicationArray
		# Build an array of each package location and get the version
		for a in "${MAUAPP[@]}"
		do
			APPVERSION=$(GetAppVersionFromXML "$a" "$CHANNEL" "$PROVIDER")
			CHKFILE="$a"
			CHKFILE+="-CHK"
			CHKVERSION=$(GetAppVersionFromXML "$CHKFILE" "$CHANNEL" "$PROVIDER")
			printf "%-55s" "     Application: $a - $APPVERSION"
			echo "$CHKFILE - $CHKVERSION"
		done
	done
done

echo
exit 0
